### ISSUE TITLE
TASK: Add fusion migrations for usage of `node.identifier` and `node.nodeAggregateIdentifier`

### ISSUE THREAD

**Issue by ahaeslich** [neos/rector#12]
**Example of old usages:**

```
@process.augment = Neos.Fusion:Augmenter {
  id = ${node.identifier}
}

@process.augment = Neos.Fusion:Augmenter {
  id = ${node.nodeAggregateIdentifier}
}
```

**Example of usage in Neos 9:**
```
@process.augment = Neos.Fusion:Augmenter {
  id = ${node.nodeAggregateId.value}
}
```

**Comment by skurfuerst** [comment]
did half of it here: https://github.com/neos/rector/commit/6bc0427016ff72c7a3188f17489a4a1e4266fa26

**Comment by skurfuerst** [comment]
second half here: https://github.com/neos/rector/commit/56a625730844effc03f26b095b287d0d1116c6d8 - all done ✅
