### ISSUE TITLE
Migrate `node.context.inBackend` to `Neos.Backend.isEditMode(request)`

### ISSUE THREAD

**Issue by mhsdesign** [neos/rector#21]
Resolves partly https://github.com/neos/neos-development-collection/issues/4396

As @mficzel said here https://github.com/neos/neos-ui/pull/3571:

> replace `Neos.Node.inBackend(node)` which is removed here https://github.com/neos/neos-development-collection/pull/4067 with `Neos.Backend.isEditMode(request) || Neos.Backend.isPreviewMode(request)`

Currently  `node.context.inBackend` is rewritten to `Neos.Node.inBackend`, but we might get rid of that method or deprecate it... 

The question is if we should provide a Flow or rector migration for existing 9.0 projects using `Neos.Node.inBackend`? - could be a simple regex ^^ (or one needs to run this regex yourself via php storm.)

search
```
Neos.Node.inBackend\([a-zA-Z]*\)
```

replace with

```
Neos.Backend.isEditMode(request) || Neos.Backend.isPreviewMode(request)
```

**Comment by mficzel** [comment]
I would only provide migrations for features that we actually released. The few existing 9.0 projects are maintained by people capable of handling this just fine.

**Comment by dlubitz** [comment]
Can we close this @mhsdesign ?

**Comment by mhsdesign** [comment]
yes see https://github.com/neos/rector/blob/e752234fbb7572e96d443e43a28c42e37dd3e75d/src/ContentRepository90/Rules/FusionContextCurrentRenderingModeRector.php
