### ISSUE TITLE
TASK: 9.0 migrate `node.context.currentRenderingMode.edit`

### ISSUE THREAD

**Issue by mhsdesign** [neos/rector#23]
`node.context` is not available anymore.

https://github.com/neos/neos-development-collection/blob/f4ed8369957209ba689cb2e1d9319e39716d6ac3/Neos.Neos/Resources/Private/Fusion/Prototypes/ContentCollection.fusion#L30

**Comment by dlubitz** [comment]
We need to specify that more in detail. I already found recgtor migrations, but AFAIS they are already outdated right?

**Fusion**
https://github.com/neos/rector/blob/618a7fde2af27629a522737bd09bacba3549e6d4/src/ContentRepository90/Rules/FusionContextLiveRector.php#L15-L15

https://github.com/neos/rector/blob/618a7fde2af27629a522737bd09bacba3549e6d4/src/ContentRepository90/Rules/FusionContextInBackendRector.php#L15-L15

https://github.com/neos/rector/blob/618a7fde2af27629a522737bd09bacba3549e6d4/src/ContentRepository90/Rules/FusionContextCurrentSiteRector.php#L22-L22

What about PHP migrations here?

And we miss migrations for `currentRenderingMode` at all.

https://github.com/neos/rector/blob/618a7fde2af27629a522737bd09bacba3549e6d4/config/set/contentrepository-90.php#L262-L283

**Comment by ahaeslich** [comment]
@mficzel updated some old migrations already before deleting the eel helper we temporarily used. So yes information in this package might be outdated.

**Comment by mficzel** [comment]
Migration seems right but I probably did not adjust the comment

**Comment by dlubitz** [comment]
That's right. I already cleaned that up: https://github.com/neos/rector/pull/27

But they are just for fusion and for example `node.context.currentRenderingMode` is still not covered, right? 

Also the other `ContentContext` methods might need some rector rewrites?

**Comment by mficzel** [comment]
Yes. We should can migrate currentRendering mode aswell.
