### ISSUE TITLE
BUG: Rector migration for usage of `node.parent` doesn't work

### ISSUE THREAD

**Issue by ahaeslich** [neos/rector#29]
- It will generate comments for lines that are using flow query operations like `parent()` or `parents()`
- The comment says `You may need to rewrite "VARIABLE.parent" to Neos.NodeAccess.findParent(VARIABLE).` But I found no matching eel helper.

**Comment by dlubitz** [comment]
Good catch! Maybe someone of the experts can tell us what the correct replacement is?
/cc @mhsdesign @mficzel @bwaidelich

**Comment by mficzel** [comment]
As I see from my cellphone flowQuery “parent”|”parents” is implemented. This migration might be not needed at all.

**Comment by dlubitz** [comment]
It's actually not FlowQuery it was the removed getter of the Node.

**Comment by mficzel** [comment]
How about converting that to q(node).parent().get(0)

**Comment by kdambekalns** [comment]
It still warns about `q(node).parents()`…
