### ISSUE TITLE
NodeSearchService removed 

### ISSUE THREAD

**Issue by pKallert** [neos/rector#43]
In https://github.com/neos/neos-development-collection/pull/4555#issue-1909993555 we removed the NodeSearchService. There was also a discussion about re-adding the Service, but was decided against: https://github.com/neos/neos-development-collection/issues/3771 

There are Upgrade instructions in the PR to migrate, but we should think about adding a comment or hint directly using rector.

**Comment by dlubitz** [comment]
```diff
- $nodes = $this->nodeSearchService->findByProperties(string $term, array $searchNodeTypes);
+ $nodes = $this->subgraph->findDescendantNodes(
+     $entryNode->nodeAggregateId,
+     FindDescendantNodesFilter::create(
+         nodeTypes: NodeTypeConstraints::create(
+             NodeTypeNames::fromStringArray($searchNodeTypes),
+             NodeTypeNames::createEmpty()
+         ),
+         searchTerm: $term,
+     )
+ );
```

**Comment by dlubitz** [comment]
We also need to check for the interface: `Neos\ContentRepository\Domain\Service\Context::NodeSearchServiceInterface`
