### ISSUE TITLE
exchange `Neos.Fusion:RawArray` and `Neos.Fusion:Attributes` prototypes

### ISSUE THREAD

**Issue by Jan3k3y** [neos/rector#47]
These prototypes are not longer a part of neos after the Update to version 9

The correct prototype in this case would be `Neos.Fusion:DataStructure` as far as I found out

**Comment by mhsdesign** [comment]
Actually for attributes there is no 1to1 replacement, see dilemma: https://github.com/neos/neos-development-collection/issues/4885

The Neos change which removed the prototypes is https://github.com/neos/neos-development-collection/pull/4537
