### ISSUE TITLE
Add comments for removed signals

### ISSUE THREAD

**Issue by Jan3k3y** [neos/rector#48]
On the Neos Sprint in Hamburg I found out that some signals have been removed and replaced with `catchUpHooks`.

It would be pretty awesome if it would be possible to get a comment if the used signal is no longer supported
Maybe with a small hint for the hooks

**Comment by dlubitz** [comment]
See https://github.com/neos/neos-development-collection/blob/c726eae5566eb394c3fcc6cc5bd24ce4e1113717/Neos.Neos/Documentation/References/NeosFusionReference.rst#L1372-L1386

**Comment by dlubitz** [comment]
We should collect, which signal we have removed first.

**Comment by dlubitz** [comment]
**Neos\ContentRepository\Domain\Model\Node**
* beforeNodeMove
* afterNodeMove
* beforeNodeCopy
* afterNodeCopy
* nodePathChanged
* beforeNodeCreate
* afterNodeCreate
* nodeAdded
* nodeUpdated
* nodeRemoved
* beforeNodePropertyChange
* nodePropertyChanged

**Neos\ContentRepository\Domain\Model\NodeData**
* nodePathChanged

**Neos\ContentRepository\Domain\Model\Workspace**
* baseWorkspaceChanged
* beforeNodePublishing
* afterNodePublishing

**Neos\ContentRepository\Domain\Repository\NodeDataRepository**
* repositoryObjectsPersisted

**Neos\ContentRepository\Domain\Service\Context**
* beforeAdoptNode
* afterAdoptNode

**Neos\ContentRepository\Domain\Service\PublishingService**
* nodePublished
* nodeDiscarded
