### ISSUE TITLE
Migrate `Node::getNodeType`

### ISSUE THREAD

**Issue by mhsdesign** [neos/rector#57]
Following code should be migrated:

For fusion:

- [x] name fetching

```diff
- ${node.nodeType.name}
+ ${q(node).nodeTypeName()} 
```

- [x] nodetype fetching

```diff
- ${node.nodeType}
+ ${Neos.Node.getNodeType(node)}
```

- [ ] For the `Node::getNodeType` removal (https://github.com/neos/neos-development-collection/pull/5021)

```diff
- $node->getNodeTypeName();
+ $node->nodeTypeName;
```

```diff
- $node->getNodeType()->getName();
+ $node->nodeTypeName->value;
```

```diff
- $nodeType->getName();
+ $nodeType->name->value;
```

(existing [migration](https://github.com/neos/rector/blob/4843c45f5bd901bd63aad0d1d0367df394e2cd1e/config/set/contentrepository-90.php#L145))

```diff
- $node->getNodeType();
+ $nodeTypeManger = ...;
+ $nodeTypeManager->getNodeType($node->nodeTypeName);
```

- [ ]  For the `NodeType::tetheredNodeTypeDefinitions` change (https://github.com/neos/neos-development-collection/pull/4906)

These rector migration would need to be adjusted so they dont pass the `$nodeType` to the methods, but `$nodeType->name`:
- NodeTypeGetAutoCreatedChildNodesRector
- NodeTypeGetTypeOfAutoCreatedChildNodeRector
- NodeTypeAllowsGrandchildNodeTypeRector

```diff
- $node->getNodeType()->getTypeOfAutoCreatedChildNode(NodeName::fromString('name'));
+ $nodeTypeManager->getTypeOfTetheredNode($node->nodeTypeName, NodeName::fromString('name'));
```

```diff
- foreach ($nodeType->getAutoCreatedChildNodes() as $rawNodeName => $childNodeType) {
-     $nodeName = NodeName::fromString($rawNodeName);
+ foreach ($nodeType->tetheredNodeTypeDefinitions as $tetheredNodeTypeDefinition) {
+     $nodeName = $tetheredNodeTypeDefinition->name;
+     $childNodeType = $nodeTypeManager->getNodeType($tetheredNodeTypeDefinition->nodeTypeName);

- $nodeType->hasAutoCreatedChildNode($nodeName);
+ $nodeType->tetheredNodeTypeDefinitions->contain($nodeName);

- $parentsNodeType->getTypeOfAutoCreatedChildNode($nodeName)->name;
+ $parentsNodeType->tetheredNodeTypeDefinitions->get($nodeName)->nodeTypeName;

- $parentsNodeType->getTypeOfAutoCreatedChildNode($nodeName);
+ $nodeTypeManager->getNodeType($parentsNodeType->tetheredNodeTypeDefinitions->get($nodeName));

- $grandParentsNodeType->allowsGrandchildNodeType($parentNodeName->value, $nodeType);
+ $nodeTypeManager->isNodeTypeAllowedAsChildToTetheredNode($grandParentsNodeType->name, $parentNodeName, $nodeType->name);
```

**Comment by mhsdesign** [comment]
@dlubitz i have the feeling that the migrations cant be possible as clean as suggested and will likely look like having an obsolete step in between (fetching the nodeType first)

```diff
- $node->getNodeType()->getName();
+ $nodeTypeManager->getNodeType($node->nodeTypeName)->name->value;
```

```diff
- $node->getNodeType()->getTypeOfAutoCreatedChildNode(NodeName::fromString('name'));
+ $nodeTypeManager->getTypeOfTetheredNode($nodeTypeManager->getNodeType($node->nodeTypeName)->name, NodeName::fromString('name'));
```

... or we can have a rector rule to normalize `$nodeTypeManager->getNodeType($node->nodeTypeName)->name` to `$node->nodeTypeName` 😂

**Comment by dlubitz** [comment]
https://github.com/neos/neos-development-collection/pull/4906#issuecomment-2035430771

> Todo these rector migration would need to be adjusted so they dont pass the `$nodeType` to the methods, but `$nodeType->name`:
> 
> * NodeTypeGetAutoCreatedChildNodesRector
> * NodeTypeGetTypeOfAutoCreatedChildNodeRector
> * NodeTypeAllowsGrandchildNodeTypeRector
