### ISSUE TITLE
This package is not simple to install

### ISSUE THREAD

**Issue by mhsdesign** [neos/rector#58]
... and also the pin on phpstan will prohibit any other version installed. This makes this hard to install.

This is unfortunate and ideally we should upgrade to rector stable 1.x from our current 0.15.8 from april 23. The upgrade is not straight forward due to many breaking changes, which also happened in patch levels (they dont do semver) https://github.com/neos/rector/pull/56.

As discussed in the weekly our last resort would be to just bundle a phar and have that installed and at a later point totally refactor this package, removing all previous rules.

cc @kitsunet @dlubitz @ahaeslich

**Comment by kdambekalns** [comment]
> (they dont do semver)

To be fair, semver.org says: _Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable._

Using 0.x is always your own risk. 😎

**Comment by dlubitz** [comment]
Documentation has been updated, so you can install the neos/rector (incl rector/rector) beside your application. So it will not interfere with other dependencies:
https://github.com/neos/rector/pull/82
