### ISSUE TITLE
Refactor node.identifier / q(node).property('_identifier') to node.id() /  q(node).id()

### ISSUE THREAD

**Issue by dlubitz** [neos/rector#62]

**Comment by mhsdesign** [comment]
Ah thanks for this ... the other things will be handled separately:

`${q(node).nodeTypeName()}` -> https://github.com/neos/rector/issues/57

`${q(node).label()}` -> https://github.com/neos/rector/issues/71


btw the fq was introduced via (just as link ^^) https://github.com/neos/neos-development-collection/pull/5046
