### ISSUE TITLE
Add test cases that test the complete set

### ISSUE THREAD

**Issue by bwaidelich** [neos/rector#79]
There are quite a lot of tests covering the behavior of each individual rector.
But so far there is no test that covers the behavior of the `contentrepository-90` ruleset itself.

IMO we should add that, because it would be a good start to report (and fix) bugs in our rector migration:
1. Extend the test case reproducing the wrong behavior
2. Fix set/rules until the tests are green again

**Comment by dlubitz** [comment]
@bwaidelich Can we close this? We added already the possibilty to test the complete set of rules and started to add tests for new cases.

**Comment by bwaidelich** [comment]
yes, thanks a lot!
